spring.application.name=market-feedback
server.port=9060
#URLs REST pour la collecte des aléas du marché
market.feedback.rest.urls[0]=https://newsapi.org/v2/everything?q=Apple&from=2026-03-05&sortBy=popularity&apiKey=12213de84a224ca5af1d28dde90068be
#URLs rss pour la collecte des aléas du marché
market.feedback.rss.urls[0]=https://www.marketwatch.com/rss/topstories
# URLs scraping pour la collecte des aléas du marché
market.feedback.scraping.urls[0]=https://www.bvmt.com.tn/
market.feedback.scraping.tags=h1, h2, h3, p, span, strong, time, div,i,em,u,ul,il
market.feedback.rss.xml-tags=title,description,articles
market.feedback.rest.json-tags=title,description,articles
