spring.application.name=market-feedback
server.port=9060
spring.data.mongodb.uri=mongodb://localhost:27017/market-feedbac

# REST
market.feedback.rest[0].url=https://newsapi.org/v2/everything
market.feedback.rest[0].method=GET
market.feedback.rest[0].enabled=true
market.feedback.rest[0].timeout=5000
market.feedback.rest[0].description=NewsAPI Apple
market.feedback.rest[0].retry=2
market.feedback.rest[0].content_path=articles


market.feedback.rest[0].params[0].key=q
market.feedback.rest[0].params[0].value=Apple
market.feedback.rest[0].params[1].key=from
market.feedback.rest[0].params[1].value=01-04-2026
market.feedback.rest[0].params[2].key=apiKey
market.feedback.rest[0].params[2].value=12213de84a224ca5af1d28dde90068be
# Source 2 ? Tesla
market.feedback.rest[1].url=https://newsapi.org/v2/everything?q=Tesla
market.feedback.rest[1].api-key=12213de84a224ca5af1d28dde90068be
market.feedback.rest[1].description=NewsAPI Tesla
market.feedback.rest[1].enabled=true
market.feedback.rest[1].method=GET
# RSS
market.feedback.rss[0].url=https://www.marketwatch.com/rss/topstories
market.feedback.rss[0].enabled=true
market.feedback.rss[0].timeout=5000
market.feedback.rss[0].description=MarketWatch Top Stories
market.feedback.rss[0].retry=3
market.feedback.rss[0].max-items=50
market.feedback.rss[0].encoding=UTF-8

# SCRAPING
market.feedback.scraping[0].url=https://www.bvmt.com.tn/
market.feedback.scraping[0].enabled=true
market.feedback.scraping[0].timeout=5000
market.feedback.scraping[0].description=BVMT Bourse Tunis
market.feedback.scraping[0].retry=3
market.feedback.scraping[0].tags=h1, h2, h3, p, span, strong, time
market.feedback.scraping[0].user-agent=Mozilla/5.0
market.feedback.scraping[0].max-depth=2

# Scheduler
scheduler.collection.cron=*/10 * * * * *
