spring.application.name=market-feedback
server.port=9060

# REST
market.feedback.rest[0].url=https://newsapi.org/v2/everything?q=Apple&from=2026-03-05&sortBy=popularity
market.feedback.rest[0].api-key=12213de84a224ca5af1d28dde90068be
market.feedback.rest[0].method=GET
market.feedback.rest[0].enabled=true
# délai maximum d'attente de réponse en millisecondes
market.feedback.rest[0].timeout=5000
# nom lisible de la source pour les logs
market.feedback.rest[0].description=NewsAPI Apple
# nombre de tentatives en cas d?échec réseau (si le timeout expire)
market.feedback.rest[0].retry=2

# RSS
market.feedback.rss[0].url=https://www.marketwatch.com/rss/topstories
market.feedback.rss[0].enabled=true
market.feedback.rss[0].timeout=5000
market.feedback.rss[0].description=MarketWatch Top Stories
market.feedback.rss[0].retry=3
# nombre maximum d'articles à récupérer par collecte(controle de quantité pour eviter la surcharge de bd)
market.feedback.rss[0].max-items=50
# encodage du flux XML
market.feedback.rss[0].encoding=UTF-8


# SCRAPING
market.feedback.scraping[0].url=https://www.bvmt.com.tn/
market.feedback.scraping[0].enabled=true
market.feedback.scraping[0].timeout=5000
market.feedback.scraping[0].description=BVMT Bourse Tunis
market.feedback.scraping[0].retry=3
market.feedback.scraping[0].tags=h1, h2, h3, p, span, strong, time
# simule un vrai navigateur pour éviter le blocage par le site(badge d'identité)
market.feedback.scraping[0].user-agent=Mozilla/5.0
# nombre de niveaux de pages à parcourir depuis l'URL principale(scrape la page principale + ses sous-pages)
market.feedback.scraping[0].max-depth=2